# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  auth-service:
    container_name: auth-service
    image: ${DOCKER_REGISTRY-}auth-service
    build:
      context: .
      dockerfile: src/AuthService.API/Dockerfile
    ports:
      - 5000:5000
    networks:
      - auth_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge
  auth_service:
    driver: bridge

volumes:
  postgres:
