version: "3.7"

services:
  auth-service:
    container_name: auth-service
    image: ${DOCKER_REGISTRY-}auth-service
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - COMPlus_EnableDiagnostics=1
    ports:
      - 5000:5000
    entrypoint:
      - dotnet
      - AuthService.API.dll
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
