# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  auth-service:
    container_name: auth-service
    image: ${DOCKER_REGISTRY-}auth-service
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile
    ports:
      - 80:80
    networks:
      - auth_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

networks:
  auth_service:
    driver: bridge